-- AlterTable
ALTER TABLE `Attempt` ADD COLUMN `lockedAt` DATETIME(3) NULL,
    ADD COLUMN `lockedReason` VARCHAR(191) NULL,
    MODIFY `status` ENUM('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'LOCKED') NOT NULL DEFAULT 'NOT_STARTED';

-- AlterTable
ALTER TABLE `AuditLog` MODIFY `action` ENUM('ADMIN_RESET_ATTEMPT', 'CHEAT_VIOLATION', 'ADMIN_RESET_PASSWORD', 'PUBLISH_RESULTS', 'HIDE_RESULTS', 'UPDATE_ANSWER_KEY', 'REGENERATE_RESULTS') NOT NULL;
